# Generated by Django 6.0.5 on 2026-05-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='admin_file',
            field=models.FileField(blank=True, null=True, upload_to='task_files/'),
        ),
    ]
